"""Contains all logic to call API and parse the return values, gives back api results in a nice way
"""
import json
import requests
from PIL import Image
from io import BytesIO
from urllib3.exceptions import NewConnectionError

from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QDialog, QVBoxLayout, QLabel, QPushButton
import controller.constants as constants

from models.user_model import UserInfo

user_info = None

def set_user_info(user_info_in: UserInfo):
    global user_info
    user_info = user_info_in

def warning(reason:str):
    """Creates a warning popup with given reason

    Args:
        reason (str): Text to be put into warning box
    """
    warning_window = QDialog()
    warning_window.setWindowTitle("Warning!!!!!")
    warning_window_layout = QVBoxLayout()
    warning_window.setLayout(warning_window_layout)


    reason_label = QLabel(reason)
    warning_window_layout.addWidget(reason_label)

    close_button = QPushButton('Close', warning_window)
    close_button.clicked.connect(warning_window.accept)
    warning_window_layout.addWidget(close_button)
    
    warning_window.exec()
    
def get_filtered_files_metadata_from_api(tags_list: list[str])->[]:
    """Actually calls the api given the tags to describe what we want like videos, etc

    Args:
        tags (list[str]): list of rules like should be a video, in inbox or archive
    """
    try:
        hydrus_key, api_port  = user_info.get_user_info()
        res = requests.get(
            url=constants.LOCALHOST+str(api_port)+constants.GET_FILE_SEARCH,
            headers={
                constants.HYDRUS_APIKEY_PARAM : hydrus_key,
            },
            params={
                "tags" : json.dumps(tags_list)
            },
            timeout= 10
        )
        file_ids = res.json()[constants.FILE_ID_JSON_KEY]
        
        res = requests.get(
            url=constants.LOCALHOST+str(api_port)+constants.GET_FILE_METADATA,
            headers={
                constants.HYDRUS_APIKEY_PARAM : hydrus_key,
            },
            params={
                constants.FILE_ID_JSON_KEY : json.dumps(file_ids)
            },
            timeout= 10
        )
        return res.json()[constants.FILE_LIST_METADATA_KEY]
    except ValueError as e:
        warning(e)
    except requests.exceptions.ConnectionError as e:
        warning("Is hydrus running and api key/port set?")
    except KeyError as e:
        warning("Nothing found for the given settings")
    except Exception as e:
        print("Caught an exception of type:", type(e).__name__, f" and error message: {e}")
        
    return None
        

def get_file_thumbnail(file_id:str)-> QPixmap:
    """Grabs a file's thumbnail as generated by hydrus. Uses API call for now

    Args:
        api_port (int): port of client api
        hydrus_key (str): key for hydrus api program
        file_id (str): id of file

    Returns:
        QPixmap: pixmap of the thumbnail
    """
    hydrus_key, api_port = user_info.get_user_info()
    res = requests.get(
        url=constants.LOCALHOST+str(api_port)+constants.GET_FILE_THUMBNAIL,
        headers={
            constants.HYDRUS_APIKEY_PARAM : hydrus_key,
        },
        params={
            "file_id": file_id
        },
        timeout= 10
    )

    pixmap = QPixmap()
    pixmap.loadFromData(res.content) #loading from bytes of contenta
    return pixmap

def get_full_image(file_id:str)-> Image:
    """Grabs a file's full resolution image. Uses API call for now and also uses PIL's image objects

    Args:
        api_port (int): port of client api
        hydrus_key (str): key for hydrus api program
        file_id (str): id of file

    Returns:
        Image: full sized Image object based on API response
    """
    hydrus_key, api_port = user_info.get_user_info()
    res = requests.get(
        url=constants.LOCALHOST+str(api_port)+constants.GET_FULL_FILE,
        headers={
            constants.HYDRUS_APIKEY_PARAM : hydrus_key,
        },
        params={
            "file_id": file_id
        },
        timeout= 10
    )
    image = Image.open(BytesIO(res.content))
    return image
